name: Deploy to Azure Container Apps

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Java
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Build with Maven
      run: mvn clean package -DskipTests

    - name: Deploy to Azure Container Apps
      uses: azure/container-apps-deploy-action@v1
      with:
        app-name: simple-rest-app
        resource-group: <your-resource-group>
        jar-path: target/simple-rest-app-0.0.1-SNAPSHOT.jar
        runtime: java
        ingress: external
        target-port: 8080
        azure-credentials: ${{ secrets.AZURE_CREDENTIALS }}
